# Generated by Django 2.0 on 2019-07-31 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
