# Generated by Django 2.0 on 2019-08-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=3000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
